/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/creer-post/': RouteRecordInfo<'/creer-post/', '/creer-post', Record<never, never>, Record<never, never>>,
    '/inscription/': RouteRecordInfo<'/inscription/', '/inscription', Record<never, never>, Record<never, never>>,
    '/notifications/': RouteRecordInfo<'/notifications/', '/notifications', Record<never, never>, Record<never, never>>,
    '/parametres/': RouteRecordInfo<'/parametres/', '/parametres', Record<never, never>, Record<never, never>>,
    '/parametres/a-propos': RouteRecordInfo<'/parametres/a-propos', '/parametres/a-propos', Record<never, never>, Record<never, never>>,
    '/parametres/abonnement': RouteRecordInfo<'/parametres/abonnement', '/parametres/abonnement', Record<never, never>, Record<never, never>>,
    '/parametres/conditions-utilisation': RouteRecordInfo<'/parametres/conditions-utilisation', '/parametres/conditions-utilisation', Record<never, never>, Record<never, never>>,
    '/parametres/conditions-vente': RouteRecordInfo<'/parametres/conditions-vente', '/parametres/conditions-vente', Record<never, never>, Record<never, never>>,
    '/parametres/politique-confidentialite': RouteRecordInfo<'/parametres/politique-confidentialite', '/parametres/politique-confidentialite', Record<never, never>, Record<never, never>>,
    '/parametres/politique-cookies': RouteRecordInfo<'/parametres/politique-cookies', '/parametres/politique-cookies', Record<never, never>, Record<never, never>>,
    '/profil/': RouteRecordInfo<'/profil/', '/profil', Record<never, never>, Record<never, never>>,
    '/rechercher/': RouteRecordInfo<'/rechercher/', '/rechercher', Record<never, never>, Record<never, never>>,
    '/reminder/': RouteRecordInfo<'/reminder/', '/reminder', Record<never, never>, Record<never, never>>,
    '/weekly/': RouteRecordInfo<'/weekly/', '/weekly', Record<never, never>, Record<never, never>>,
  }
}
